# Übung Lineare Algebra (10 Punkte)

Diese kleine Übung soll die Implementierung von grundlegenden arithmetischen Opertationen auf Vektoren und Matrizen wiederholen. 

Bitte implementieren Sie die notwendigen Methoden in der Datei **ak1163051/lineare_algebra.py** auf Basis des Datentyps **Liste** und verifizieren Sie ihre eigene Implementierungen mit der entsprechenden Operation aus dem Numpy-Modul in diesem Notebook, falls möglich. Ein Beispiel ist mit Addition und Subtraktion der Vektoren $\vec{a}$ und $\vec{b}$ gegeben.


In [2]:
# Initialization of basic modules and global parameters... 
from lineare_algebra import * 
import numpy as np
import random

# create vectors a and b with 10 digits between 0-255
vec_a = random.sample(range(255), 10)
vec_b = random.sample(range(255), 10)

print ("Vektor a: ", vec_a)
print ("Vektor b: ", vec_b)

('Vektor a: ', [150, 85, 240, 59, 8, 43, 167, 230, 219, 48])
('Vektor b: ', [1, 102, 9, 163, 144, 162, 142, 122, 251, 201])


## Addition und Subtraktion von Vektoren

Berechnen Sie Betrag und Differenz von Vektoren nach folgendem Prinzip:

$$
\begin{equation}
    \vec{a} + \vec{b} 
    = 
    \begin{pmatrix}
    a_1\\ 
    a_2\\ 
    a_3
    \end{pmatrix} 
    +
    \begin{pmatrix}
    b_1\\ 
    b_2\\ 
    b_3
    \end{pmatrix}
    =
    \begin{pmatrix}
    a_1 + b_1\\ 
    a_2 + b_2\\ 
    a_3 + b_3
    \end{pmatrix}
\end{equation}
$$
$$
\begin{equation}
    \vec{a} - \vec{b} 
    = 
    \begin{pmatrix}
    a_1\\ 
    a_2\\ 
    a_3
    \end{pmatrix} 
    -
    \begin{pmatrix}
    b_1\\ 
    b_2\\ 
    b_3
    \end{pmatrix}
    =
    \begin{pmatrix}
    a_1 - b_1\\ 
    a_2 - b_2\\ 
    a_3 - b_3
    \end{pmatrix}
\end{equation}
$$


In [3]:
# Addition
add_result = vector_add(vec_a,vec_b)
print ("Result of vector addition:", add_result)
print ("Are the operations arithmetically equal?", np.array_equal(add_result, np.add(vec_a,vec_b)))

# Subtraction - please implement the methode in lineare_algebra.py 
sub_result = vector_sub(vec_a,vec_b)
print ("Result of vector subtraction:", sub_result)
print ("Are the operations arithmetically equal?", np.array_equal(sub_result, np.subtract(vec_a,vec_b)))

('Result of vector addition:', [243, 237, 117, 382, 132, 157, 288, 324, 193, 187])
('Are the operations arithmetically equal?', True)
('Result of vector subtraction:', [169, -213, 91, 6, 28, -7, 156, 46, 133, -119])
('Are the operations arithmetically equal?', True)


## Multiplikation von Vektoren mit einem Skalar (0,5 Punkt)

Berechenen Sie die Multiplikation von einem Skalar und einem Vektoren nach folgendem Prinzip:

$$
\begin{equation}
    r * \vec{a}
    = 
    r
    \begin{pmatrix}
    a_1\\ 
    a_2\\ 
    a_3
    \end{pmatrix} 
    =
    \begin{pmatrix}
    ra_1\\ 
    ra_2\\ 
    ra_3
    \end{pmatrix}
\end{equation}
$$

In [4]:
# your code
r = 25
vec_mul_result = vector_scalar_mul(r, vec_a)
print ("Result of vector subtraction:", vec_mul_result)
print ("Are the operations arithmetically equal?", np.array_equal(vec_mul_result, np.multiply(r,vec_a)))

('Result of vector subtraction:', [5150, 300, 2600, 4850, 2000, 1875, 5550, 4625, 4075, 850])
('Are the operations arithmetically equal?', True)


## Skalarprodukt (dot product) von Vektoren (1 Punkte)

Berechnen Sie das Skalarprodukt von zwei Vektoren nach folgendem Prinzip:

$$
\begin{equation}
    \vec{a} * \vec{b} 
    = 
    \begin{pmatrix}
    a_1\\ 
    a_2\\ 
    a_3
    \end{pmatrix} 
    *
    \begin{pmatrix}
    b_1\\ 
    b_2\\ 
    b_3
    \end{pmatrix}
    =
    a_1 * b_1 + a_2 * b_2 + a_3 * b_3
\end{equation}
$$

In [5]:
# your code (numpy: https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html)
vec_dot_result = vector_dot(vec_a, vec_b)
print ("Result of vector subtraction:", vec_dot_result)
print ("Are the operations arithmetically equal?", np.array_equal(vec_dot_result, np.dot(vec_a,vec_b)))

('Result of vector subtraction:', 108915)
('Are the operations arithmetically equal?', True)


## Erzeugen einer Matrize (1 Punkte)
Erzeugen Sie mit Hilfe einer Methode eine Matrize mit der Dimension 10x10 von Zufallswerten zwischen 0 und 255.

In [6]:
mat_A = create_random_matrix(10,10)
# print ("Matrix A: ", mat_A)
print("[")
for x in mat_A:
    print(x)
print("]")

[
[193, 189, 147, 99, 23, 127, 254, 74, 162, 62]
[67, 162, 32, 30, 154, 159, 207, 77, 200, 125]
[160, 26, 53, 137, 193, 183, 173, 43, 57, 1]
[45, 184, 197, 189, 35, 138, 123, 209, 185, 90]
[125, 89, 142, 76, 58, 126, 8, 148, 243, 214]
[96, 147, 89, 62, 59, 118, 107, 234, 136, 190]
[6, 82, 199, 109, 94, 82, 127, 237, 89, 192]
[197, 68, 72, 89, 224, 62, 57, 218, 215, 231]
[177, 147, 214, 83, 40, 113, 211, 22, 151, 73]
[65, 17, 97, 126, 114, 93, 209, 105, 200, 220]
]


## Vektor-Matrix-Multiplikation (1 Punkte)

Berechnen Sie das Produkt aus Vektor a und Matrix A nach folgendem Prinzip:
$$
    \begin{equation}
    A*\vec{x} 
    = 
    \begin{pmatrix}
    a_{11}  &\cdots & a_{1n} \\ 
    \vdots & \ddots & \vdots \\ 
    a_{m1} & \cdots & a_{mn}
    \end{pmatrix}
    *
    \begin{pmatrix}
    x_{1} \\ 
    \vdots \\ 
    x_{n} 
    \end{pmatrix}
    =
    \begin{pmatrix}
    a_{11}x_1  &\cdots & a_{1n}x_n \\ 
     & \vdots &  \\ 
    a_{m1}x_1 & \cdots & a_{mn}x_n
    \end{pmatrix}
    \end{equation}
$$

In [7]:
# your code (numpy: https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html)
mat_A = create_random_matrix(10,10)
vec_mat_mul_result = matrix_vector_mul(mat_A, vec_a)

print ("Result of vector subtraction:", vec_mat_mul_result)
print ("Are the operations arithmetically equal?", np.array_equal(vec_mat_mul_result, np.dot(mat_A, vec_a)))

('Result of vector subtraction:', [211395, 229109, 174663, 107915, 143112, 159588, 140803, 210713, 207286, 185460])
('Are the operations arithmetically equal?', True)


## Transponente einer Matrix (1 Punkte)

Manipulieren Sie die Matrix A, sodass die Transponente entsteht, siehe:
    
$$
    \begin{equation}
    A
    = 
    \begin{pmatrix}
    a_{11}  &\cdots & a_{1n} \\ 
    \vdots & \ddots & \vdots \\ 
    a_{m1} & \cdots & a_{mn}
    \end{pmatrix}
    \end{equation}
$$   
$$
    \begin{equation}
    A^T
    = 
    \begin{pmatrix}
    a_{11}  &\cdots & a_{m1} \\ 
    \vdots & \ddots & \vdots \\ 
    a_{1n} & \cdots & a_{mn}
    \end{pmatrix}
    \end{equation}
$$   

In [8]:
# your code (https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.transpose.html)

print np.transpose(mat_A)
mat_transpose_result = matrix_transpose(mat_A)
print ("Result of vector subtraction:", mat_transpose_result)
print ("Are the operations arithmetically equal?", np.array_equal(mat_transpose_result, np.transpose(mat_A)))

[[ 96 192 203 180 175 134 157 233  74 189]
 [178 172 215   1  52 185 132 100 132 191]
 [217 240 202  44 248 247  61 188  87  72]
 [152  62 178   3  78 123  42 246 224  14]
 [ 25  63   9  33 178 166  41 158  48 232]
 [149 212 102  25  51   1  71  20  25  42]
 [227 237 109   8   3  64 137 236 219 218]
 [149 238  20  86 114 135 217   0 196 220]
 [245 159 189 246 157 136  59 117 243 126]
 [187 206 225  99   3 162 106 254 228  79]]
('Result of vector subtraction:', [[96, 192, 203, 180, 175, 134, 157, 233, 74, 189], [178, 172, 215, 1, 52, 185, 132, 100, 132, 191], [217, 240, 202, 44, 248, 247, 61, 188, 87, 72], [152, 62, 178, 3, 78, 123, 42, 246, 224, 14], [25, 63, 9, 33, 178, 166, 41, 158, 48, 232], [149, 212, 102, 25, 51, 1, 71, 20, 25, 42], [227, 237, 109, 8, 3, 64, 137, 236, 219, 218], [149, 238, 20, 86, 114, 135, 217, 0, 196, 220], [245, 159, 189, 246, 157, 136, 59, 117, 243, 126], [187, 206, 225, 99, 3, 162, 106, 254, 228, 79]])
('Are the operations arithmetically equal?', True)
