# Übung Lineare Algebra (10 Punkte)

Diese kleine Übung soll die Implementierung von grundlegenden arithmetischen Opertationen auf Vektoren und Matrizen wiederholen. 

Bitte implementieren Sie die notwendigen Methoden in der Datei **ak1163051/lineare_algebra.py** auf Basis des Datentyps **Liste** und verifizieren Sie ihre eigene Implementierungen mit der entsprechenden Operation aus dem Numpy-Modul in diesem Notebook, falls möglich. Ein Beispiel ist mit Addition und Subtraktion der Vektoren $\vec{a}$ und $\vec{b}$ gegeben.


In [1]:
# Initialization of basic modules and global parameters... 
from lineare_algebra import * 
import numpy as np
import random

# create vectors a and b with 10 digits between 0-255
vec_a = random.sample(range(255), 10)
vec_b = random.sample(range(255), 10)

print ("Vektor a: ", vec_a)
print ("Vektor b: ", vec_b)

('Vektor a: ', [20, 11, 225, 217, 43, 148, 232, 29, 174, 162])
('Vektor b: ', [224, 153, 37, 205, 103, 184, 159, 242, 217, 49])


## Addition und Subtraktion von Vektoren

Berechnen Sie Betrag und Differenz von Vektoren nach folgendem Prinzip:

$$
\begin{equation}
    \vec{a} + \vec{b} 
    = 
    \begin{pmatrix}
    a_1\\ 
    a_2\\ 
    a_3
    \end{pmatrix} 
    +
    \begin{pmatrix}
    b_1\\ 
    b_2\\ 
    b_3
    \end{pmatrix}
    =
    \begin{pmatrix}
    a_1 + b_1\\ 
    a_2 + b_2\\ 
    a_3 + b_3
    \end{pmatrix}
\end{equation}
$$
$$
\begin{equation}
    \vec{a} - \vec{b} 
    = 
    \begin{pmatrix}
    a_1\\ 
    a_2\\ 
    a_3
    \end{pmatrix} 
    -
    \begin{pmatrix}
    b_1\\ 
    b_2\\ 
    b_3
    \end{pmatrix}
    =
    \begin{pmatrix}
    a_1 - b_1\\ 
    a_2 - b_2\\ 
    a_3 - b_3
    \end{pmatrix}
\end{equation}
$$


In [2]:
# Addition
add_result = vector_add(vec_a,vec_b)
print ("Result of vector addition:", add_result)
print ("Are the operations arithmetically equal?", np.array_equal(add_result, np.add(vec_a,vec_b)))

# Subtraction - please implement the methode in lineare_algebra.py 
sub_result = vector_sub(vec_a,vec_b)
print ("Result of vector subtraction:", sub_result)
print ("Are the operations arithmetically equal?", np.array_equal(sub_result, np.subtract(vec_a,vec_b)))

('Result of vector addition:', [244, 164, 262, 422, 146, 332, 391, 271, 391, 211])
('Are the operations arithmetically equal?', True)
('Result of vector subtraction:', [-204, -142, 188, 12, -60, -36, 73, -213, -43, 113])
('Are the operations arithmetically equal?', True)


## Multiplikation von Vektoren mit einem Skalar (0,5 Punkt)

Berechenen Sie die Multiplikation von einem Skalar und einem Vektoren nach folgendem Prinzip:

$$
\begin{equation}
    r * \vec{a}
    = 
    r
    \begin{pmatrix}
    a_1\\ 
    a_2\\ 
    a_3
    \end{pmatrix} 
    =
    \begin{pmatrix}
    ra_1\\ 
    ra_2\\ 
    ra_3
    \end{pmatrix}
\end{equation}
$$

In [3]:
# your code
r = 25
vec_mul_result = vector_scalar_mul(r, vec_a)
print ("Result of vector subtraction:", vec_mul_result)
print ("Are the operations arithmetically equal?", np.array_equal(vec_mul_result, np.multiply(r,vec_a)))

('Result of vector subtraction:', [500, 275, 5625, 5425, 1075, 3700, 5800, 725, 4350, 4050])
('Are the operations arithmetically equal?', True)


## Skalarprodukt (dot product) von Vektoren (1 Punkte)

Berechnen Sie das Skalarprodukt von zwei Vektoren nach folgendem Prinzip:

$$
\begin{equation}
    \vec{a} * \vec{b} 
    = 
    \begin{pmatrix}
    a_1\\ 
    a_2\\ 
    a_3
    \end{pmatrix} 
    *
    \begin{pmatrix}
    b_1\\ 
    b_2\\ 
    b_3
    \end{pmatrix}
    =
    a_1 * b_1 + a_2 * b_2 + a_3 * b_3
\end{equation}
$$

In [4]:
# your code (numpy: https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html)
vec_dot_result = vector_dot(vec_a, vec_b)
print ("Result of vector subtraction:", vec_dot_result)
print ("Are the operations arithmetically equal?", np.array_equal(vec_dot_result, np.dot(vec_a,vec_b)))

('Result of vector subtraction:', 180236)
('Are the operations arithmetically equal?', True)


## Erzeugen einer Matrize (1 Punkte)
Erzeugen Sie mit Hilfe einer Methode eine Matrize mit der Dimension 10x10 von Zufallswerten zwischen 0 und 255.

In [5]:
mat_A = create_random_matrix(10,10)
# print ("Matrix A: ", mat_A)
print("[")
for x in mat_A:
    print(x)
print("]")

[
[189, 44, 8, 206, 250, 247, 34, 122, 132, 206]
[78, 228, 105, 87, 135, 17, 242, 27, 9, 137]
[5, 251, 47, 11, 56, 228, 12, 29, 208, 91]
[146, 112, 94, 174, 160, 174, 252, 191, 141, 12]
[26, 224, 228, 108, 38, 135, 187, 16, 122, 170]
[41, 213, 214, 26, 194, 211, 90, 52, 174, 125]
[93, 28, 173, 111, 203, 136, 196, 89, 180, 123]
[48, 210, 149, 218, 61, 99, 50, 116, 126, 207]
[22, 50, 206, 91, 121, 182, 253, 52, 183, 117]
[69, 187, 93, 195, 69, 191, 140, 105, 36, 238]
]


## Vektor-Matrix-Multiplikation (1 Punkte)

Berechnen Sie das Produkt aus Vektor a und Matrix A nach folgendem Prinzip:
$$
    \begin{equation}
    A*\vec{x} 
    = 
    \begin{pmatrix}
    a_{11}  &\cdots & a_{1n} \\ 
    \vdots & \ddots & \vdots \\ 
    a_{m1} & \cdots & a_{mn}
    \end{pmatrix}
    *
    \begin{pmatrix}
    x_{1} \\ 
    \vdots \\ 
    x_{n} 
    \end{pmatrix}
    =
    \begin{pmatrix}
    a_{11}x_1  &\cdots & a_{1n}x_n \\ 
     & \vdots &  \\ 
    a_{m1}x_1 & \cdots & a_{mn}x_n
    \end{pmatrix}
    \end{equation}
$$

In [6]:
# your code (numpy: https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html)
mat_A = create_random_matrix(10,10)
vec_mat_mul_result = matrix_vector_mul(mat_A, vec_a)

print ("Result of vector subtraction:", vec_mat_mul_result)
print ("Are the operations arithmetically equal?", np.array_equal(vec_mat_mul_result, np.dot(mat_A, vec_a)))

('Result of vector subtraction:', [170560, 185702, 113097, 235638, 166257, 165365, 74560, 172244, 156529, 168795])
('Are the operations arithmetically equal?', True)


## Transponente einer Matrix (1 Punkte)

Manipulieren Sie die Matrix A, sodass die Transponente entsteht, siehe:
    
$$
    \begin{equation}
    A
    = 
    \begin{pmatrix}
    a_{11}  &\cdots & a_{1n} \\ 
    \vdots & \ddots & \vdots \\ 
    a_{m1} & \cdots & a_{mn}
    \end{pmatrix}
    \end{equation}
$$   
$$
    \begin{equation}
    A^T
    = 
    \begin{pmatrix}
    a_{11}  &\cdots & a_{m1} \\ 
    \vdots & \ddots & \vdots \\ 
    a_{1n} & \cdots & a_{mn}
    \end{pmatrix}
    \end{equation}
$$   

In [7]:
# your code (https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.transpose.html)

print np.transpose(mat_A)
mat_transpose_result = matrix_transpose(mat_A)
print ("Result of vector subtraction:", mat_transpose_result)
print ("Are the operations arithmetically equal?", np.array_equal(mat_transpose_result, np.transpose(mat_A)))

[[ 63  55   6 232 218 189 106 141 239 182]
 [ 48 233 150 145  87 160  72  99 208 194]
 [148 117 128 251 122  45   9 227 212 235]
 [  6 183  61 226 231 175   8  43 192  83]
 [136 105  82 122 117 138 105  90  26 250]
 [137 227 100  28   6  25 150 191 191 196]
 [195 157 176 202 214 224  35 100   9  38]
 [200 124 242 252  20  55 182 245   3  41]
 [120 159   3 248 135 210  87 186  83 237]
 [223  63  16 106  23  74  78  81  87   7]]
('Result of vector subtraction:', [[63, 55, 6, 232, 218, 189, 106, 141, 239, 182], [48, 233, 150, 145, 87, 160, 72, 99, 208, 194], [148, 117, 128, 251, 122, 45, 9, 227, 212, 235], [6, 183, 61, 226, 231, 175, 8, 43, 192, 83], [136, 105, 82, 122, 117, 138, 105, 90, 26, 250], [137, 227, 100, 28, 6, 25, 150, 191, 191, 196], [195, 157, 176, 202, 214, 224, 35, 100, 9, 38], [200, 124, 242, 252, 20, 55, 182, 245, 3, 41], [120, 159, 3, 248, 135, 210, 87, 186, 83, 237], [223, 63, 16, 106, 23, 74, 78, 81, 87, 7]])
('Are the operations arithmetically equal?', True)
